import Head from "next/head";
import Test12 from "../components/test12";
import UpBtn from "../components/upBtn/UpBtn";
import Container from "../components/container/Container";
import Pegination from "../components/pegination/Pegination";
import React, { useEffect, memo } from "react";
import { useDispatch, useSelector } from "react-redux";
import Carousel from "../components/carousel/carousel";
import ShowCase from "../components/show-case/ShowCase";
import Layout from "../components/Layout/Layout";
// import { HOne } from "../styled-components/styledComponents";


function Home() {

  const d = useSelector((s) => s);
  console.log(d, "mana");


  return (
    <>
      <Head>
        <title>Logo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.jpg" />
      </Head>
      

      <Container>
        <ShowCase />
        {/* <h2>{t("Welcome_to_React")}</h2> */}
        <Test12 />
        <Pegination />
      </Container>
    </>
  );
}
export default memo(Home);
